Controllers/CarrinhoCompraController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using projeto_livraria.Data;
using projeto_livraria.Models;
using projeto_livraria.ViewModel;

namespace AppWeb.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly LivrariaContext _LivrariaContext;
        private CarrinhoCompra _CarrinhoCompra;

        public CarrinhoCompraController(LivrariaContext LivrariaContext,
                                        CarrinhoCompra CarrinhoCompra)
        {
            _LivrariaContext = LivrariaContext;
            _CarrinhoCompra = CarrinhoCompra;

        }

        public IActionResult Index()
        {
            var itens = _CarrinhoCompra.GetCarrinho_Item();
            _CarrinhoCompra.Carrinho_Item = itens;

            var CarrinhoCompraViewModel = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _CarrinhoCompra,
                CarrinhoCompraTotal = _CarrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(CarrinhoCompraViewModel);
        }

        [Authorize]
        [Route("CarrinhoCompra/Index")]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int IdLivro)
        {
            var livroSelecionado = _LivrariaContext.Livro.FirstOrDefault(p => p.IdLivro == IdLivro);

            if (livroSelecionado != null)
            {
                _CarrinhoCompra.AdicionarAoCarrinho(livroSelecionado, 1);
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public RedirectToActionResult RemoverItemNoCarrinhoCompra(int IdLivro)
        {
            var livroSelecionado = _LivrariaContext.Livro.FirstOrDefault(p => p.IdLivro == IdLivro);

            if (livroSelecionado != null)
            {
                _CarrinhoCompra.RemoverDoCarrinho(livroSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/LivrosController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using projeto_livraria.Data;
using projeto_livraria.Models;
using projeto_livraria.ViewModel;

namespace projeto_livraria.Controllers
{
    public class LivrosController : Controller 
    {
        // private readonly ILogger<LivrosController> _logger;
        private readonly LivrariaContext _context;
        public LivrosController(LivrariaContext context)
        {
             _context = context;
        }
        [Route("Livros/List")]
        public IActionResult List()
        {
            ViewBag.livros = "livro";
        
            var LivrosListViewModel = new LivroListViewModel(); 
            LivrosListViewModel.Livro = _context.Livro;
            return View(LivrosListViewModel);
        }
        [Route("Home/Details")]
        public IActionResult Details(int IdLivro)
        {
            var livro = _context.Livro.FirstOrDefault(I=> I.IdLivro == IdLivro);
            if(livro == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            return View(livro);
        }
        public IActionResult Busca(string buscaString)
        {
            string _buscaString = buscaString;
            IEnumerable<Livro> livro;

            if (string.IsNullOrEmpty(_buscaString))
            {
                livro = _context.Livro.OrderBy(l => l.IdLivro);
            }
            else
            {
                livro = _context.Livro.Where(l => l.Titulo.ToLower().Contains(_buscaString.ToLower()));
            }
            return View("~/Views/Livros/List.cshtml", new LivroListViewModel {Livro = livro});
        }
    }
}

Views/Shared/LivroResumo.cshtml
@model projeto_livraria.Models.Livro;
@{
    ViewData["Title"] = "Home Page";
}
<div>            
    <article class="card p-2 m-3 width-cards col-3 col-md-3 border-primary rounded">
        @if (@Model.Imagem != null)
        {
           <td>
                 @{
                     var imgSrc = String.Format("data:image/jpeg;base64,{0}", @Model.Imagem);
                  }
                 <img src='@imgSrc' class="card-img-top posicao-imagem-card " />
            </td>
        }
        <div class="card-body">
        <h5>
            <a asp-asp-controller="Titulo" asp-action="Details" asp-route-Idlivro="@Model.IdLivro">"@Model.Titulo"</a>
        </h5>
        <p class="card-text">Preço : @Model.Preco.ToString("C")</p>
        <div class="AddToCart Text-right">
        </div>
            <p class="button ">
                <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-IdLivro="@Model.IdLivro">
                    Incluir no Carrinho
                </a>
            </p>        
        </div>
    </article>                                           
</div> 
      

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Biblioteca</title>
    <title>@ViewData["Title"] - Biblioteca</title>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/css/site.css">
</head>
<body>      
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="col container ml-0 mr-0">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="img-logo rounded" src="~/images/Layout/logo2.jpeg">
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                
                <form class="navbar-form custom navbar-right ml-5" asp-controller="Livros" asp-action="Busca" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control input-size mt-3 mb-0" placeholder="Procurar Livro" name="buscaString" value="@ViewData["buscaString"]">
                    </div>
                </form>

                <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
                    <ul class="navbar-nav">
                        <li><a class="nav-item nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                        </li> <a class="nav-item nav-link" asp-area="" asp-controller="Livros" asp-action="List">Livros</a></li>
                        <li><a class="nav-item nav-link" href="#" data-toggle="modal"
                                data-target="#modal-fale-conosco">Fale conosco</a></li>
                        <li class=" icon-carrinho">@await Component.InvokeAsync("CarrinhoCompraResumo")</li>
                    </ul>
                </div>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>
    </header>
        
    <div class="container-fluid p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modal-fale-conosco" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Fale conosco</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Vendas: 5020-3322</p>
                    <p>SAC: 5020-3330</p>
                    <p>E-mail: faleconosco@livraria207.com.br</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

     <footer class="pt-4 my-md-5 pt-md-5 border-top mr-sm-0 layout-foolter">
 
        <div class="row">
          <div class="ml-sm-5 ml-5 col-sm-2">
            <img class="mb-2" src="~/images/imagens-foolter/icon-livro.png" alt="" width="50" height="50">
            <small class="d-block mb-3 text-muted"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">© 2020</font></font></small>
          </div>
          <div class="col-6 col-md">
            <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Recursos</font></font></h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mais informações</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Recurso aleatório</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Característica da equipe</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Coisas para desenvolvedores</font></font></a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sobre</font></font></h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Equipe</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Localizações</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Privacidade</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Termos e Condições</font></font></a></li>
            </ul>
          </div>
          <div class="mr-5 ml-sm-5">
            <h5 class="ml-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Formas de Pagamento</font></font></h5>
            <ul class="list-unstyled text-small">
              <img src="~/images/imagens-foolter/pagamento.png" class="mx-auto d-block w-100" alt="...">
            </ul>
          </div>
        </div>
      </footer>

    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>