Areas/Admin/Controllers/AdminLivrosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using projeto_livraria.Data;
using projeto_livraria.Models;
using System.Linq;
using System.Threading.Tasks;
using ReflectionIT.Mvc.Paging;

namespace projeto_livraria.Area.Admin.Controllers
{
    [Area("Admin")]
    public class AdminLivrosController : Controller
    {
        private readonly LivrariaContext _context;

        public AdminLivrosController(LivrariaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string filter, int pageindex = 1, string sort = "Titulo")
        {
            var resultado = _context.Livro.AsQueryable();
            
            if (!string.IsNullOrWhiteSpace(filter))
            {
                resultado = resultado.Where(l => l.Titulo.Contains(filter));
            }

            var model = await PagingList.CreateAsync(resultado, 5, pageindex, sort, "Nome");

            model.RouteValue = new RouteValueDictionary { { "filter", filter } };

            return View(model);
        }

        [HttpGet]
        [Route("Admin/AdminLivros/Details")]
        public IActionResult Details()
            {
                return View();
            }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro
                .FirstOrDefaultAsync(m => m.IdLivro == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Admin/AdminLivros/Create")]
        public IActionResult Create()
            {
                return View();
            }
        public async Task<IActionResult> Create([Bind("IdLivro,Titulo,Autor,Editora,Descricao,Ano,Numero_de_Paginas,Acabamento,Idioma,Pais,Altura,Largura,Peso,Preco")] Livro livro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(livro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }
        [HttpPut]

        // GET: Admin/AdminLivros/Edit/5
        [Route("Admin/AdminLivros/Edit")]
        public IActionResult Edit()
            {
                return View();
            }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro.FindAsync(id);
            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        // POST: Admin/AdminLivros/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdLivro,Titulo,Autor,Editora,Descricao,Ano,Numero_de_Paginas,Acabamento,Idioma,Pais,Altura,Largura,Peso,Preco")] Livro livro)
        {
            if (id != livro.IdLivro)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(livro.IdLivro))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Admin/AdminLivros/Delete/5
        [HttpGet]
        [Route("Admin/AdminLivros/Delete")]
        public IActionResult Delete()
            {
                return View();
            }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro
                .FirstOrDefaultAsync(m => m.IdLivro == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Admin/AdminLivros/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Admin/AdminLivros/DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var livro = await _context.Livro.FindAsync(id);
            _context.Livro.Remove(livro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivroExists(int id)
        {
            return _context.Livro.Any(e => e.IdLivro == id);
        }
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Biblioteca</title>
    <title>@ViewData["Title"] - Admin</title>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/css/site.css">
</head>
<body>      
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand font-titulo tamanho-titulo" href="https://localhost:5001/Admin" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
                    <ul class="navbar-nav">
                        <li><a class="nav-item nav-link" href="https://localhost:5001/Admin/AdminLivros/Index" asp-area="Admin" asp-controller="AdminLivros" asp-action="Index">Livros</a></li>
                        <li><a class="nav-item nav-link" href="#" data-toggle="modal" data-target="#modal-fale-conosco">Fale conosco</a></li>
                        <li><a class="nav-item nav-link" asp-area="Admin" asp-controller="Admin" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
        
    <div class="container-fluid p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modal-fale-conosco" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Fale conosco</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Vendas: 5020-3322</p>
                    <p>SAC: 5020-3330</p>
                    <p>E-mail: faleconosco@Livraria207.com.br</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

     <footer class="pt-4 my-md-5 pt-md-5 border-top mr-sm-0 layout-foolter">
 
        <div class="row">
          <div class="ml-sm-5 ml-5 col-sm-2">
            <img class="mb-2" src="~/images/imagens-foolter/icon-livro.png" alt="" width="50" height="50">
            <small class="d-block mb-3 text-muted"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">© 2020</font></font></small>
          </div>
          <div class="col-6 col-md">
            <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Recursos</font></font></h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mais informações</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Recurso aleatório</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Característica da equipe</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Coisas para desenvolvedores</font></font></a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sobre</font></font></h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Equipe</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Localizações</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Privacidade</font></font></a></li>
              <li><a class="text-muted" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Termos e Condições</font></font></a></li>
            </ul>
          </div>
          <div class="mr-5 ml-sm-5">
            <h5 class="ml-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Formas de Pagamento</font></font></h5>
            <ul class="list-unstyled text-small">
              <img src="~/images/imagens-foolter/pagamento.png" class="mx-auto d-block w-100" alt="...">
            </ul>
          </div>
        </div>
      </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>